name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@b00551441a6fa3d528f3443dbff264a934b6e316
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Install gems
        run: |
          gem install rubocop
          gem install rubocop-minitest
          gem install rubocop-performance

      - name: Run Rubocop
        run: rubocop --except Metrics
