name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@93287a1fa82c6ddbb6d8db978df4b0119cd8879f
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Install gems
        run: |
          gem install rubocop
          gem install rubocop-minitest
          gem install rubocop-performance

      - name: Run Rubocop
        run: rubocop --except Metrics
