name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@7d546f4868fb108ed378764d873683f920672ae2
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Install gems
        run: |
          gem install rubocop
          gem install rubocop-minitest
          gem install rubocop-performance

      - name: Run Rubocop
        run: rubocop --except Metrics
